### ISSUE TITLE
Sequential command execution

### ISSUE THREAD

**Issue by vallentin** [grego/caretaker#1]
It would be nice to be able to specify, that a command must be executed sequentially. In other words, if the command is executing and while running another change event is detected. Then it must wait to re-execute the command, until the one running has finished.

I have a tool that renders all markdown files in a directory to HTML pages along with an index page. I can see a potential issue if two instances of the command are running sequentially.

Actually, looking in the README, I can see the following command fail in the same case. If instance A is "being slow" e.g. waiting on IO, and instance B finished first. Then when instance A finishes, the final `style.css` could be outdated.

```toml
[[watch]]
name = "compile sass"
path = "sass"
command = "sassc -t compressed sass/style.scss static/style.css"
```
