### ISSUE TITLE
Files moved with mv into watched target directory do not trigger the action

### ISSUE THREAD

**Issue by JuryA** [grego/caretaker#8]
#### System details
- OS/Platform name and version: `Microsoft Windows 10 Enterprise, Ver. 21H2 (OS Build 19044.18889)`
- Rust version (if building from source): `rustc 1.59.0`
- Caretaker version: `caretaker 0.2.4`
- Filesystem type and options: `/dev/sdb on / type ext4 (rw,relatime,discard,errors=remount-ro,data=ordered)`
- Linux Kernel version: `Linux 5.10.102.1-microsoft-standard-WSL2 # 1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Linux Subsystem: `WSL2 (Ubuntu 22.04.1 LTS)`
- Running as a privileged user (root, System): **NO**
- Running in a container: **NO**

#### What you did (as detailed as you can)
My `.watch.toml`:
```toml
[[watch]]
# What does the command do?
name = "print hello"
# Where to look for changes?
path = "test-watcher/queue/*.sql"
# What to execute on change?
command = "cat \"$EVENT_PATH\" && mv \"$EVENT_PATH\" test-watcher/processed"
```
I created 3 files: `test1.sql`, `test2.sql`, `test3.sql` and used `mv`:
`mv *.sql test-watcher/queue/`

#### What you expected
I expected that `mv` trigger action 3x.
(Tested 3 times back and forth...)

#### What happened
Nothing happened - files were moved successfully.

If I did the same experiment with `cp`, everything was processed as expected:
```shell
❯ caretaker watch
Watching 1 path for changes...
"/home/<redacted>/test-watcher/queue/test1.sql" changed, running print hello
pasdfa
"/home/<redacted>/usu/test-watcher/queue/test2.sql" changed, running print hello
asdkjsah
"/home/<redacted>/usu/test-watcher/queue/test3.sql" changed, running print hello
sadsaf
```
